# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

  update-if-needed:
    
    runs-on: ubuntu-latest

    steps:

    - name: Show debug info
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        git status
        echo "${GITHUB_CONTEXT}"

# First check out the merge commit.
    - uses: actions/checkout@v2

# Run the 'check' that for this test always fails.
    - name: check (always fails)
      id: check_step
      continue-on-error: true
      run: exit 1

# Now we try to checkout the base branch.
    - name: checkout base branch
      if: steps.check_step.outcome == 'Failure'
    - uses: actions/checkout@v2
      with:
        clean: true
        ref: ${{ github.head_ref }}

    - name: update a file
      if: steps.check_step.outcome == 'Failure'
      run: |
        echo date > hello.txt
        git add hello.txt

    - name: Create Pull Request with Changes
      if: steps.check_step.outcome == 'Failure'
      uses: peter-evans/create-pull-request@v2
      with:
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
