# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

  continue-on-error:
    runs-on: ubuntu-latest

    steps:
    - name: failing-command
      id: fail_step
      run: exit 1

    - name: show context
      env:
        STEPS_CONTEXT: ${{ toJson(steps.fail_step.outcome) }}
      run: echo "$STEPS_CONTEXT"

    - name: react to success
      if: steps.fail_step.outcome == 'Success'
      run: echo "step succeded"

    - name: on-fail
      if: steps.fail_step.outcome == 'Failure'
      run: echo "fail step failed"

    - name: second-fail-step
      run: echo "step still failed"

    - name: on-fail-2
      if: failure() && steps.fail_step.outcome == 'Failure'
      run: echo "::error ::The fail step failed!"

  push-some-changes:
    runs-on: ubuntu-latest

    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: add a file
      run: date > date.txt

    - name: add file to repo
      run: git add date.txt

    - name: Show debug info
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        git status
        echo "${GITHUB_CONTEXT}"

    - name: Create Pull Request with Changes
      uses: peter-evans/create-pull-request@v2
      with:
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
